### ISSUE TITLE
Watchlist not working

### ISSUE THREAD

**Issue by robby28-11** [ozdemirozcelik/pairs-api#1]
Hi,

installed V4 - thank you for your nice work! 
But for me the watchlist is not working. Do you have any ideas?

Here the failure: 

```
TemplateNotFound
jinja2.exceptions.TemplateNotFound: watch.html

Traceback (most recent call last)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
return original_handler(e)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
return original_handler(e)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/ubuntu/pairs-api/app.py", line 561, in watchlist
return render_template(
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
return self._load_template(name, globals)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
template = self.loader.load(self, name, self.make_globals(globals))
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
source, filename, uptodate = self.get_source(environment, name)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
return self._get_source_fast(environment, template)
File "/home/ubuntu/pairs-api/pairs-env/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: watch.html
```

**Comment by ozdemirozcelik** [comment]
Hi, seems that the template file is missing.
I will soon upload it and it should fix the problem.

**Comment by robby28-11** [comment]
Yep, that was it. Watchlist working now. Thanks!
